on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  main:
    name: CI
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        buildType: [
          Debug,
          RelWithDebInfo,
        ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          ./installClang16.sh
          sudo apt-get update
          sudo --preserve-env apt-get install --assume-yes \
              cmake \
              ninja-build
      - name: Configuration
        env:
          CC: clang-16
          CXX: clang++-16
        run: |
          cmake -B build -G Ninja -S . \
            -D Clang_DIR=/usr/lib/cmake/clang-16 \
            -D LLVM_DIR=/usr/lib/llvm-16/cmake \
            -D CMAKE_BUILD_TYPE=${{matrix.buildType}}
      - name: Build
        run: cmake --build build
      - name: Test
        run: |          
          ctest --test-dir build

          cmake \
            -D CMAKE_EXPORT_COMPILE_COMMANDS=ON \
            -B buildRepoUsingPlugin -S repo-using-plugin
          cmake --build buildRepoUsingPlugin

          clang-tidy \
            --checks='coveo-awesomeprefixcheck' \
            --load build/lib/libAwesomePrefixCheck.so \
            -p buildRepoUsingPlugin/compile_commands.json \
            repo-using-plugin/src/code.cpp
